version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SETTINGS: ${SETTINGS}
    platform: linux/amd64

    ports:
      - 8000:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - SETTINGS_CONFIG=${SETTINGS}
      - DJANGO_SETTINGS_MODULE=${SETTINGS}
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    platform: linux/amd64
    ports:
      - '6379:6379'
    expose:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
      args:
        SETTINGS: ${SETTINGS}
    platform: linux/amd64
    depends_on:
      - redis
